### ISSUE TITLE
plugin types not generated

### ISSUE THREAD

**Issue by balazssoltesz** [rjbma/dtsgenerator-express-route-types#4]
hello, 
im using ur plugin in a new project with typescript 4.0.3 and plugin types not generated in the d.ts file. 
my dtsgen.json:
```
{  
    "plugins": {
        "dtsgenerator-express-route-types": {
            "placeholderType": "any",
            "routeTypeName": "RouteHandler"
        }
    }
}
```
dtsgen command:
./node_modules/dtsgenerator/bin/dtsgen ./src/app/openapi.json --out openapi.d.ts

**Comment by rjbma** [comment]
Hi @balazssoltesz, sorry for the late reply.

Unfortunately, with that description alone I can't figure out what the problem is. Did you add the plugin to your `package.json`?
I just setup an example project using the plugin [here](https://github.com/rjbma/dtsgenerator-express-route-types-example), maybe you can take a look at it.

**Comment by balazssoltesz** [comment]
hello @rjbma,

thank you for your response. Iam trying with an openapi 3.0,1 specification. Can it be the problem?
Everything else is the same as your config.

**Comment by rjbma** [comment]
That doesn't seem to be it, just upgraded the pet store spec to v3 and it appears to be working fine.

May be some specific OpenAPI feature in your spec that is not currently supported.

To be clear, what happens if you replace the `api.json` spec in the example repository withou your own and run the generator? Does the `.d.ts` file get generated at all?

**Comment by balazssoltesz** [comment]
ohh, i have got it. If i install ts-node ^9, then plugin types not generated. Otherwise it is ok. 
Thank you for your help!

**Comment by balazssoltesz** [comment]
mystic, its random. sometimes it is ok, sometimes not. im testing more...

**Comment by balazssoltesz** [comment]
ok. you can reproduce the error the following way:

- clone your example into a dir
- delete package-lock.json
- delete api.d.ts
- run "npm i"
- run "npx dtsgen api.json --out api.d.ts"

After that there is no plugin's type in the generated ts file at me.

**Comment by rjbma** [comment]
Weird, it's working for me, even when after following the steps you describe.

I will say this: the project I'm working on that's using the plugin runs the generator using `typescript@3`
Also, **dtsgenerator** depends on `typescript@3` and `ts-node@8`, so maybe that's were the problem coming from.

Can you try downgrading your typescript version and see if you can replicate the problem?

**Comment by balazssoltesz** [comment]
yes. i can confirm, when i removed localy installed typescript@4 and reinstalled dtsgenerator and your plugin, then everything works as expected. 

thank you for your help!
